### ISSUE TITLE
`xnames` for inline citations?

### ISSUE THREAD

**Issue by ali-ramadhan** [Azzaare/Bibliography.jl#3] opened 2020-07-12 22:02 UTC
Was wondering if it's within the scope of the `xnames` function to return short versions of the list suitable for inline citations. For example, for the author list "Kenneth J. Arrow, Leonid Hurwicz, Hirofumi Uzawa" we would have

```julia
julia> xnames(entry, last_names_only=true, max_authors=1)
"Arrow et al."

julia> xnames(entry, last_names_only=true, max_authors=2)
"Arrow & Hurwicz et al."

julia> xnames(entry, last_names_only=true)
"Arrow, Hurwicz, & Uzawa"
```

or maybe this functionality deserves its own separate function. But with keyword arguments perhaps there just needs to be one nice `xnames` function.

**Comment by Azzaare** [comment] 2020-07-13 00:54
It definitely is within its scope ! I am also in favor of keywords arguments.

What about using only one keyword argument for names though?
`xnames(entry, names=some_name_format_enum, max_authors=1)`
It is less intuitive, but I can think of at least 4-5 ways to write names, and more might come.

Eventually, having dedicated functions that use some specific combinations of keyword arguments in the different x"some field" functions will happen. For instance, something like `export_citations("somefile.bib", format="apa")`
And of course, we could have a default function for documenter, such as `bibtex_to_documenter("file.bib", some_keywords ...)`

**Comment by ali-ramadhan** [comment] 2020-07-13 11:56
Ah yeah that makes sense! Certainly there are multiple ways so options like `names=:last` or `names=:full` would be nice. I'm not super familiar with all the different formats but I imagine different people prefer different formats too.

**Comment by Azzaare** [comment] 2020-07-13 12:51
I will base the output of the xname function on [this document](http://maverick.inria.fr/~Xavier.Decoret/resources/xdkbibtex/bibtex_summary.html#standard). I will go with two output for the moment: `:last, :full`

But we will have to consider cases such as First-Second Third von Last. We can shorten it as
- F.-S. von Last
- F.-S. T. von Last
- First-Second T. von Last 
and so on ...

**Comment by Azzaare** [comment] 2020-07-13 14:46
@ali-ramadhan can you test `names=:last` on branch `test_xnames` for your test plugin?

If it works for you I will add the max_authors arg, and probably change the structure in BibInternal so that the authors are already stored as `BibtexName` from the start with

```julia
struct BibtexName  
    particle::String
    last::String
    junior::String
    first::String
    middle::String  
end
```

**Comment by ali-ramadhan** [comment] 2020-07-13 16:33
Awesome, that was fast! I tried with a small test `.bib` file on the `test_xnames` branch but unfortunately it doesn't seem to work as the output is the same.

```bibtex
shell> cat test.bib
@article{ahu61,
   author={Arrow, Kenneth J. and Leonid Hurwicz and Hirofumi Uzawa},
   title={Constraint qualifications in maximization problems},
   journal={Naval Research Logistics Quarterly},
   volume={8},
   year=1961,
   pages={175-191},
   doi={10.1002/nav.3800080206}
}

@book{ab94,
   author = {Charalambos D. Aliprantis and Kim C. Border},
   year = {1994},
   title = {Infinite Dimensional Analysis},
   publisher = {Springer},
   address = {Berlin},
   url = {https://www.springer.com/gp/book/9783540295860}
}
```

```julia
julia> xnames(BIBLIOGRAPHY["ahu61"])
"Kenneth J. Arrow , Leonid Leonid Hurwicz , Hirofumi Hirofumi Uzawa "

julia> xnames(BIBLIOGRAPHY["ahu61"], names=:last)
"Kenneth J. Arrow , Leonid Leonid Hurwicz , Hirofumi Hirofumi Uzawa "

julia> xnames(BIBLIOGRAPHY["ahu61"], names=:full)
"Kenneth J. Arrow , Leonid Leonid Hurwicz , Hirofumi Hirofumi Uzawa "

julia> xnames(BIBLIOGRAPHY["ahu61"], names=:zzz)
"Kenneth J. Arrow , Leonid Leonid Hurwicz , Hirofumi Hirofumi Uzawa "

julia> xnames(BIBLIOGRAPHY["ab94"])
"Charalambos D. D. Aliprantis , Kim C. C. Border "

julia> xnames(BIBLIOGRAPHY["ab94"], names=:last)
"Charalambos D. D. Aliprantis , Kim C. C. Border "

julia> xnames(BIBLIOGRAPHY["ab94"], names=:full)
"Charalambos D. D. Aliprantis , Kim C. C. Border "
```

I'm also guessing it should probably error if `names` is not `:last` or `:full`.

**Comment by Azzaare** [comment] 2020-07-13 21:07
Sorry, I had no time to test by myself yesterday. I will try with your plugin repo later and fix it. 

Thank you for testing.

**Comment by Azzaare** [comment] 2020-07-14 05:04
OK, last version of Bibliography is working with the correct output. Names are stored as the struct above in BibInternal.

I will submit to the registry once BibInternal and BibParser have been merged. If you want to test asap, you can checkout master.

For the error, I will put one later, but a Warning might be preferable ("Info: switching to full_name printing as the arg was not within [some list]")

**Closed by Azzaare** 2020-07-14 05:04 UTC
Labels: enhancement

**Comment by Azzaare** [comment] 2020-07-14 12:13
Just in case, from v0.2.0 (now available), the issue is solved. Feel free to test :D

**Comment by ali-ramadhan** [comment] 2020-07-14 14:58
Awesome, thanks for fixing these issues so quickly!

Looks like it works now!
```julia
julia> Bibliography.xnames(bib["ahu61"])
"Kenneth J. Arrow , Leonid Hurwicz , Hirofumi Uzawa "

julia> Bibliography.xnames(bib["ahu61"], names=:last)
" Arrow , Hurwicz , Uzawa "
```

Would be nice to have an `and` or `&` for the last author but I think this would come with a `max_authors` kwarg as you suggested in your earlier post.

For now the citations work and look pretty good so I'm very happy!
